name: Pytest

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[huggingface,extra,dev]
      - name: Lint
        run: |
          python -m flake8 simple_typing_application --show-source
          python -m flake8 tests --show-source
      - name: Type check
        run: |
          python -m mypy simple_typing_application
          python -m mypy tests
      - name: Test
        run: |
          python -m pytest -m "not integrate"
